# Generated by Django 2.2.9 on 2023-01-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230125_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, default='-пусто-', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='posts.Group'),
        ),
    ]
